### ISSUE TITLE
Get number of steps inside a StepBody

### ISSUE THREAD

**Issue by arctouch-carlosottoboni** [danielgerlag/workflow-es#23]
Is there a way to get the count of steps of a workflow inside the StepBody?

**Comment by danielgerlag** [comment]
Yup, you can use the `context` parameter that gets passed to the `run` method to access it.

This is what the context object looks like - https://github.com/danielgerlag/workflow-es/blob/master/core/src/models/step-execution-context.ts

**Comment by arctouch-carlosottoboni** [comment]
Thanks Daniel.
