### ISSUE TITLE
Multiple instances of step running at the same time

### ISSUE THREAD

**Issue by arctouch-ricardobonfim** [danielgerlag/workflow-es#30]
I'm having an issue where multiple instances of the same step run "at the same time".

I was wondering what are the chances of multiple instances of my application (running with load-balancer) hitting the database and getting the same RunnableInstances?

I looked into the code base and saw the function below, which seems to not work well with multiple instances, right?
```
private async process(self: PollWorker): Promise<void> {                
    self.logger.info("pollRunnables " + " - now = " + Date.now());
    //TODO: lock
    try {        
        let runnables = await self.persistence.getRunnableInstances();
        for (let item of runnables) {                    
            self.queueProvider.queueForProcessing(item, QueueType.Workflow);
        }
    }
    catch (err) {
        self.logger.error("Error running poll: " + err);
    }

    try {
        let events = await self.persistence.getRunnableEvents();
        for (let item of events) {
            self.queueProvider.queueForProcessing(item, QueueType.Event);
        }
    }
    catch (err) {
        self.logger.error("Error running poll: " + err);
    }
}
```

**Comment by danielgerlag** [comment]
If you are running multiple instances of your app, then you need to setup a shared queue and lock manager, see: https://github.com/danielgerlag/workflow-es#multi-node-clusters

As you see here, the lock manager will have to grant a lock before a workflow can be executed:
https://github.com/danielgerlag/workflow-es/blob/master/core/src/services/workflow-queue-worker.ts#L56

**Comment by arctouch-ricardobonfim** [comment]
I'm currently using the mysql provider for persistence, would I have to implement the whole lock system?

and thanks for the fast reply!

**Comment by danielgerlag** [comment]
The persistence provider you choose has nothing to do with the concurrency providers you use.
Currently, the only ones available are for Azure - https://github.com/danielgerlag/workflow-es/tree/master/providers/workflow-es-azure

I am working on a Redis implementation, should be ready in a week or two.

**Comment by vimalraj-a** [comment]
@danielgerlag Redis implementation of concurrency will be a great help. I was planning for creating those for my usecase.

**Comment by danielgerlag** [comment]
It's already been published

https://github.com/danielgerlag/workflow-es/tree/master/providers/workflow-es-redis
