### ISSUE TITLE
Error handling question

### ISSUE THREAD

**Issue by moltar** [danielgerlag/workflow-es#39]
Hey Daniel (fellow Canadian here 🇨🇦),

Great work on the package. Looks very thought-out and I think has a big future and potential!

One question I have is about error handling.

There are no docs about what happens when a step fails.

Is that by design? Do you think this is outside the scope of this package and that business logic should handle the errors?

E.g. if error -> branch to an error handling step, which then waits & re-queues or marks as failed in the app in some way. Is this how the app should handle it?

Thanks.

**Comment by danielgerlag** [comment]
Yes, sorry I realize this is missing from the tutorials.
You can configure error behavior per step

```
.onError(WorkflowErrorHandling.Retry, 5000)
```

The various options are defined here: https://github.com/danielgerlag/workflow-es/blob/master/core/src/models/workflow-error-handling.ts

You can also define saga transactions with compensation steps: https://github.com/danielgerlag/workflow-es/blob/master/es2017-guide.md#saga-transactions

**Comment by moltar** [comment]
Ok, great, thanks! That does answer my question.

And this creates another question.

Is there a way to retain state between retries? E.g. lets say a count of retries. Or is this something that is external to this library?

Thanks.

**Comment by danielgerlag** [comment]
Internally it does track the number of retries in [this field](https://github.com/danielgerlag/workflow-es/blob/master/core/src/models/execution-pointer.ts#L17)
However, it's not currently exposed anywhere but we could probably build something around that.

**Comment by moltar** [comment]
I was wondering about some generic state, retry count is just an example. But something like an object that is held and given back to retries.

**Comment by danielgerlag** [comment]
You can access the `context` object within a step to access the execution pointer [here](https://github.com/danielgerlag/workflow-es/blob/master/core/src/models/step-execution-context.ts#L8)
 and then the retry count on it [here](https://github.com/danielgerlag/workflow-es/blob/master/core/src/models/execution-pointer.ts#L17)

**Comment by moltar** [comment]
Thanks!
