### ISSUE TITLE
Poll Worker Interval Override

### ISSUE THREAD

**Issue by jan-kacina** [danielgerlag/workflow-es#41]
Hi Daniel,
I'd like to set `processTimer` interval of `PollWorker` to 1 000 milliseconds.

Is there any strong reason to be set to default 10 000 milliseconds without possibility to override it programmatically? Is there any other risk than increased consumption of processor's resources?

Thanks and regards,,
Jan

PS: I used your `workflow-core` before on .NET projects and I'm glad I can continue with the same solution in Javascript as wel. Big thanks!

**Comment by danielgerlag** [comment]
I don't see a reason why this can't be configured. 10 seconds was just an arbitrary default.

**Comment by jan-kacina** [comment]
Thanks a lot, Daniel.
Looking forrward to incorporate your Conductor, if suitable in the future :)
