### ISSUE TITLE
waitFor - multiple events

### ISSUE THREAD

**Issue by gary-menzel** [danielgerlag/workflow-es#7]
Hello,

This is more of a question than a bug.  I've just started looking at using workflow-es and it looks straightforward for my needs.

However, I've been trying to play around with the idea of a workflow that would have multiple waitFor steps but that are not sequential (that is, think of 3 people having to "approve" the workflow before it could enter the step - those approvals could be in any order).

While I can put multiple waitFor steps in, the engine seems to get confused.

I have thought about using a "while" but I would still need to persist some data to know when all of the previous events had been triggered.

[sorry if you prefer this type of question via a different forum]

**Comment by danielgerlag** [comment]
Hi,

You might be able to achieve this with a `.forEach` step, as it runs the children in parallel

https://github.com/danielgerlag/workflow-es/blob/master/es2017-guide.md#parallel-foreach

Let me know if this helps?

**Comment by gary-menzel** [comment]
I was also looking at for-each (basically I am running up each of the examples in my own test environment and playing with them to understand how it all operates).

I think I can do it in a single event. If I were to execute some code in that step that checked all the conditions then returned true or false, that should control the execution of the next step - correct?

Also, I am struggling to get the OUTCOME sample working. Maybe I am not understanding what it should be doing.  I am guessing it is supposed to be checking the 'result' returned as the outcome in the first step. But that doesn't seem to be working.

Other than these few gaps, I am really liking how tidy this code is. Thanks for making it open source.

**Comment by gary-menzel** [comment]
I'll close this for now(although I am still stuck on the 'outcome' example) as I have worked out a way to do this with the `waitFor` sitting inside a `while`. Something like this...

```
.startWith(...)
.while(/* exit state is not reached */)
  .do((this)=>then
    .startWith(...)
      .input((step,data)=>{...})
      .output((step,data)->{
        // the output step can check if the final compound state is reached in related data
        // and set an appropriate variable that is checked in the .while()
        ...
      })
      .waitFor("interim-event", data=>data.myId)
    .then(...)
  )
.then(/* finished */)
)
```

**Comment by danielgerlag** [comment]
Hi Gary,

This project is actually a port of it's .NET counterpart - which is a little further ahead in terms of features...

That version has a `.Parallel()` feature:
https://github.com/danielgerlag/workflow-core/wiki/06.-Control-Structures#parallel-paths

I can look into updating workflow-es with some of the functionality that I have put into the .NET version?

**Comment by gary-menzel** [comment]
Hi Daniel,

I was wondering about a Parallel feature (although I am pretty sure I can handle my use-case with the sample flow above).

I noticed you had a version across a number of platforms.  I also wondered if you had worked from any core references for the architecture.
