### ISSUE TITLE
Questions regarding .when(...)

### ISSUE THREAD

**Issue by gary-menzel** [danielgerlag/workflow-es#8]
I have pretty much worked out all the sample code now but am still struggling with the `.when(...)` element.  What I (think I) do understand....
- `.when(...)` provides alternatives for outcome of the step they are attached to.
- each .`then(..)` attached to the `.when(...)` provides the sequence of steps that will take place if the condition for the `.when(...)` is met.

What I don't understand is how to trigger the condition. The sample has constants set in it and the "outcome" step sets the `.outcome(...)` on the `ExecutionResult` BUT, it seems like both `.when(...)` steps are always being triggered as the workflow runs (regardless of the value in the outcome).

From the sample, I would have assumed (given the input of 7) that the outcome would be set to 1 and subsequently trigger TaskC and TaskD. However, the source code implies that `.when(...)` takes a function.

Additionally, I assume the `.name(...)` important with regard to this process as it seems related to the `.end(...)` after each `.when(...)`.

I feel like I am missing something....

Regards,
Gary

**Comment by gary-menzel** [comment]
Once again (as I suspected would happen) just after I posted my question I solved it....

The sample has `.when(0)` and `.when(1)` but (as in the source) the parameter should be a function. I turned on logging and got a similarly worded error.

So, by changing the code to `.when(x=>0)` and `.when(x=>1)` I was able to have it perform as expected for different types of input. This means the sample for Outcome is incorrect.

I'll close this off now.

Regards,
Gary

**Comment by danielgerlag** [comment]
Hi Gary,

I think that sample is out of date, the first version did not use a lambda.  I will fix that.  Please feel free to email me directly if you have any questions or require assistance - daniel@gerlag.ca

Kind regards

**Comment by gary-menzel** [comment]
Thanks Daniel,

I think I have most of my knowledge about your package now but I think I am only scratching the surface. I have some plans with how I want to use it - so I may hit some more snags and will contact you directly.

Regards,
Gary
